// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe_shop/internal/dao/internal"
)

// internalGoodsOptionsDao is internal type for wrapping internal DAO implements.
type internalGoodsOptionsDao = *internal.GoodsOptionsDao

// goodsOptionsDao is the data access object for table goods_options.
// You can define custom methods on it to extend its functionality as you wish.
type goodsOptionsRepo struct {
	internalGoodsOptionsDao
}

var (
	// GoodsOptionsRepo is globally public accessible object for table goods_options operations.
	GoodsOptionsRepo = goodsOptionsRepo{
		internal.NewGoodsOptionsDao(),
	}
)

// Fill with you ideas below.
