// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe_shop/internal/dao/internal"
)

// internalOrderGoodsCommentsDao is internal type for wrapping internal DAO implements.
type internalOrderGoodsCommentsDao = *internal.OrderGoodsCommentsDao

// orderGoodsCommentsDao is the data access object for table order_goods_comments.
// You can define custom methods on it to extend its functionality as you wish.
type orderGoodsCommentsDao struct {
	internalOrderGoodsCommentsDao
}

var (
	// OrderGoodsComments is globally public accessible object for table order_goods_comments operations.
	OrderGoodsComments = orderGoodsCommentsDao{
		internal.NewOrderGoodsCommentsDao(),
	}
)

// Fill with you ideas below.
