// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe_shop/internal/dao/internal"
)

// internalOrderGoodsDao is internal type for wrapping internal DAO implements.
type internalOrderGoodsDao = *internal.OrderGoodsDao

// orderGoodsDao is the data access object for table order_goods.
// You can define custom methods on it to extend its functionality as you wish.
type orderGoodsRepo struct {
	internalOrderGoodsDao
}

var (
	// OrderGoodsRepo is globally public accessible object for table order_goods operations.
	OrderGoodsRepo = orderGoodsRepo{
		internal.NewOrderGoodsDao(),
	}
)

// Fill with you ideas below.
